CREATE TABLE realestate_agents (
    agent_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    phone VARCHAR(20),
    email VARCHAR(100)
);

CREATE TABLE realestate_listings (
    listing_id INT PRIMARY KEY,
    agent_id INT,
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    price DECIMAL(12,2),
    bed INT,
    bath DECIMAL(3,1),
    square_feet INT,
    listed_date DATE,
    description TEXT,
    FOREIGN KEY (agent_id) REFERENCES realestate_agents(agent_id)
);

INSERT INTO realestate_agents (agent_id, first_name, last_name, phone, email) VALUES
(1, 'John', 'Smith', '555-123-4567', 'john.smith@example.com'),
(2, 'Emily', 'Johnson', '555-234-5678', 'emily.johnson@example.com'),
(3, 'Michael', 'Brown', '555-345-6789', 'michael.brown@example.com'),
(4, 'Sarah', 'Davis', '555-456-7890', 'sarah.davis@example.com'),
(5, 'David', 'Miller', '555-567-8901', 'david.miller@example.com'),
(6, 'Olivia', 'Wilson', '555-678-9012', 'olivia.wilson@example.com');

INSERT INTO realestate_listings
(listing_id, agent_id, address, city, state, price, bed, bath, square_feet, listed_date, description) VALUES
(1,  3, '12 Maple Court',       'New York',    'NY',  599000.00, 4, 3.0, 2300, '2025-01-10',
 'Stunningly renovated four-bedroom townhouse in a vibrant, tree-lined neighborhood. The open-concept main floor features wide-plank hardwood, a chef''s kitchen with quartz countertops and stainless appliances, and a bright dining area that opens to a private courtyard perfect for entertaining. The primary suite includes an ensuite bath with dual vanities and custom closets; excellent transit access and nearby parks.'),
(2,  1, '34 Elm Street',        'Buffalo',     'NY',  279900.00, 3, 1.5, 1250, '2025-01-12',
 'Charming single-level ranch offering original hardwood floors and abundant natural light. The updated kitchen includes modern cabinetry and a breakfast nook; the lower level is partially finished and ideal for a home office or playroom. Large, fully fenced backyard, new roof, and convenient driveway parking.'),
(3,  5, '56 Oak Avenue',        'Rochester',   'NY',  345000.00, 4, 2.5, 1890, '2025-01-18',
 'Classic Colonial thoughtfully updated for modern living. The renovated kitchen features premium cabinetry and stainless-steel appliances; formal dining and a family room with fireplace make this a great home for gatherings. Private rear patio and established landscaping — close to schools and commuter routes.'),
(4,  2, '78 Pine Lane',         'New York',    'NY',  485000.00, 3, 2.0, 1750, '2025-01-21',
 'Meticulously maintained three-bedroom residence with bright living spaces and a recently updated kitchen with stone counters. The fenced yard and deck provide excellent outdoor living; primary bedroom with generous closet space. Walkable to neighborhood cafes, transit stops, and community parks.'),
(5,  6, '90 Birch Road',        'Buffalo',     'NY',  310000.00, 3, 2.0, 1500, '2025-01-25',
 'Well-appointed home blending classic charm and contemporary upgrades. Highlights include refinished hardwood floors, a remodeled main bath, and a light-filled eat-in kitchen with custom shelving. Off-street parking and a private backyard bordered by mature trees for added privacy.'),
(6,  4, '101 Sycamore Ave',     'New York',    'NY',  368000.00, 3, 2.0, 1620, '2025-01-30',
 'Bright and airy three-bedroom home offering an open living plan and updated mechanicals. The first-floor living area flows into a modern kitchen with stainless appliances; upstairs features comfortable bedrooms and a renovated full bath. Short commute to transit hubs and local amenities.'),
(7,  3, '121 Riverbend Drive',  'Wilmington',  'DE',  410000.00, 4, 2.5, 2010, '2025-02-05',
 'Spacious family home in a calm Wilmington neighborhood, featuring a light-filled living room, formal dining room, and an upgraded kitchen with granite counters. The primary suite includes an ensuite bath and walk-in closet. Private, landscaped backyard and a sunroom overlooking the grounds; walking distance to parks and schools.'),
(8,  2, '131 Harbor Avenue',    'Dover',       'DE',  295000.00, 3, 2.0, 1490, '2025-02-10',
 'Charming cape-cod style residence with tasteful interior updates throughout. The main level offers a cozy living room with fireplace and a renovated kitchen, while the upstairs bedrooms are comfortable and bright. Attached garage, fenced yard, and an excellent commuter location near shopping and schools.'),
(9,  5, '201 Parkside Blvd',    'Philadelphia', 'PA', 325000.00, 3, 2.0, 1420, '2025-02-14',
 'Lovely rowhome in a sought-after neighborhood featuring a redesigned kitchen with ample storage, a sunny living room, and a finished lower level perfect for a media room or home office. The private rooftop deck offers city views and a great entertaining space; close to transit, dining, and parks.'),
(10, 1, '215 Linden Terrace',   'Philadelphia', 'PA', 285000.00, 2, 1.5, 1100, '2025-02-18',
 'Updated two-bedroom rowhome offering efficient city living with modern finishes and durable flooring throughout. The kitchen has been refreshed with stainless appliances, and the lower level provides flexible storage or work space. Steps from neighborhood cafes and easy access to public transportation.'),
(11, 6, '227 Willow Street',     'Pittsburgh',   'PA', 389000.00, 4, 3.0, 2200, '2025-02-22',
 'Substantial single-family property with versatile living areas and high-end finishes. The open-concept kitchen includes custom cabinetry, while the primary suite offers a spa-like bath and privacy. Professionally landscaped backyard and oversized two-car garage make this an ideal family home.'),
(12, 4, '238 Chestnut Lane',    'Philadelphia', 'PA', 360000.00, 3, 2.0, 1560, '2025-02-26',
 'Beautifully updated interior blending modern appointments with classic details. The living spaces are bright and airy, and the kitchen includes quartz counters and generous cabinet space. Finished lower level provides additional living area; excellent access to schools and community amenities.'),
(13, 2, '249 Elmwood Drive',    'Pittsburgh',   'PA', 301000.00, 3, 2.0, 1340, '2025-03-01',
 'Comfortable split-level home with recent improvements including a remodeled kitchen and updated windows. The backyard is private and easy to maintain; nearby parks and schools add to the family-friendly appeal. Driveway parking and a practical floorplan for daily living.'),
(14, 5, '260 Magnolia Road',    'Harrisburg',   'PA', 295000.00, 3, 2.0, 1350, '2025-03-05',
 'Adorable three-bedroom bungalow with refreshed interior paint and new flooring. The cheerful kitchen and comfortable living areas make this an ideal starter home; full basement offers storage or future expansion potential. Close to city conveniences and commuter routes.'),
(15, 3, '271 Oak Terrace',      'Philadelphia', 'PA', 342000.00, 3, 2.0, 1480, '2025-03-09',
 'Charming urban residence with thoughtful updates. The open living/dining area creates a welcoming flow, and the updated kitchen is suitable for everyday cooking and entertaining. Private backyard and proximity to parks and neighborhood restaurants.'),
(16, 1, '283 Pinecrest Court',  'Pittsburgh',   'PA', 375000.00, 3, 2.5, 1670, '2025-03-13',
 'Well-maintained three-bedroom home with an updated kitchen, comfortable master suite, and finished attic space suitable for an office or guest area. The property features mature landscaping and a patio for outdoor gatherings; close to major routes and local amenities.'),
(17, 6, '295 Harbor Lane',      'Philadelphia', 'PA', 309000.00, 3, 2.0, 1410, '2025-03-17',
 'Neatly updated rowhome offering modern conveniences and efficient use of space. The kitchen has contemporary finishes, and the living areas receive ample natural light. Short walk to transit and neighborhood shops; a practical and stylish city home.'),
(18, 4, '307 Commonwealth Ave', 'Boston',       'MA',  575000.00, 4, 3.0, 2200, '2025-03-21',
 'Beautifully maintained single-family home in an excellent school district. The first floor features formal living and dining rooms, plus a light-filled family room adjacent to a gourmet kitchen with ample storage. Upstairs the primary suite includes a generous closet and a well-appointed bath; easy access to transit and local amenities.'),
(19, 2, '318 Garden Street',    'Cambridge',    'MA',  499000.00, 3, 2.0, 1620, '2025-03-25',
 'Charming three-bedroom townhome steps from public transit and neighborhood shops. The interior showcases exposed brick accents and refinished hardwood floors, and the kitchen has been thoughtfully updated with modern counters. Private roof deck provides city views and a peaceful outdoor spot.'),
(20, 5, '329 Beacon Hill',      'Boston',       'MA',  540000.00, 3, 2.0, 1580, '2025-03-29',
 'Historic-feel rowhome with modern systems and tasteful finishes. High ceilings and oversized windows flood the rooms with light; the remodeled kitchen is perfect for both everyday use and entertaining. Walkable to restaurants, parks, and cultural attractions.'),
(21, 1, '341 Maple Street',     'Worcester',    'MA',  268000.00, 3, 1.5, 1180, '2025-04-02',
 'Affordable and move-in ready three-bedroom home ideal for growing families. The property includes an updated bath, a functional eat-in kitchen, and a fenced yard for pets and children. Recent improvements include energy-efficient windows and upgraded mechanicals.'),
(22, 6, '353 Orchard Lane',     'Boston',       'MA',  455000.00, 3, 2.0, 1440, '2025-04-06',
 'Bright and welcoming residence located close to transit and neighborhood conveniences. The renovated kitchen and updated baths provide modern comfort while the living spaces retain period charm. Handy storage and a small, private garden make outdoor time easy.'),
(23, 4, '365 River Road',       'Richmond',     'VA',  360000.00, 3, 2.0, 1600, '2025-04-10',
 'Classic three-bedroom home offering a pleasing blend of period detail and contemporary updates. Formal living and dining create an elegant setting while the renovated kitchen and baths provide modern convenience. Located near parks and local dining with easy commuter access.'),
(24, 2, '377 Harborview Drive', 'Richmond',     'VA',  348000.00, 3, 2.0, 1520, '2025-04-14',
 'Comfortable residence with an updated layout and family-friendly flow. The kitchen opens to a dining area and the backyard is fully fenced for privacy. Recent mechanical upgrades include a newer HVAC system and improved insulation; great neighborhood for families.'),
(25, 5, '389 Bay Street',       'Norfolk',      'VA',  289000.00, 3, 2.0, 1300, '2025-04-18',
 'Bright, well-kept three-bedroom home situated close to waterfront amenities and neighborhood restaurants. The interior features an open main floor and updated kitchen appliances; covered porch and small yard ideal for morning coffee. Easy access to marinas and local parks.'),
(26, 1, '401 Colonial Road',    'Alexandria',   'VA',  525000.00, 4, 2.5, 2000, '2025-04-22',
 'Charming, well-preserved home in historic Alexandria featuring generous room sizes and timeless architectural detail. The updated kitchen and baths blend seamlessly with original hardwood floors and decorative moldings. Walkable to shops, dining, and public transportation — a true city-suburban hybrid.'),
(27, 3, '413 Elmwood Ave',      'Norfolk',      'VA',  310000.00, 3, 2.0, 1450, '2025-04-26',
 'Nicely updated ranch-style home offering single-floor living and an efficient footprint. The interior flows well from living room to kitchen; three bedrooms provide flexibility for a home office or guest space. Located close to shopping, schools, and major commuting corridors.'),
(28, 6, '425 Oak Hollow',       'Richmond',     'VA',  375000.00, 4, 2.5, 1850, '2025-04-30',
 'Well-maintained single-family home in a sought-after Richmond neighborhood. The interior features a renovated kitchen with ample counter space, a comfortable family room, and a private backyard with patio. Strong curb appeal and proximity to local parks and schools.'),
(29, 2, '437 Harbor Lane',      'Baltimore',    'MD',  360000.00, 3, 2.5, 1700, '2025-05-04',
 'Attractive three-bedroom single-family home in a convenient Baltimore location. Features include a modern kitchen with upgraded counters, a bright living room with large windows, and a fully fenced backyard. Close to shopping, transit, and major commuter routes.'),
(30, 5, '449 Seaview Court',    'Annapolis',    'MD',  590000.00, 4, 3.5, 2500, '2025-05-08',
 'Luxuriously appointed four-bedroom home in a desirable Annapolis neighborhood. High-end finishes include a chef''s kitchen with premium appliances, custom millwork, and a finished lower level suitable for guests or recreation. Expansive deck and private yard with tasteful landscaping; short drive to marinas and downtown.')
